### ISSUE TITLE
Installation Error:  Building wheel for scikit-learn (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by SC-TO** [nestauk/ojd_daps_skills#194]
Dear all, 

I am trying to install ojd-daps-skills via the command

`pip install ojd-daps-skills`

however, the installation stopped due to errors in building wheels for scikit-learn.  The error message is rather long, see here: 
[error_log.txt](https://github.com/nestauk/ojd_daps_skills/files/12192474/error_log.txt)

I extracted some as follows: 

... 
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (pyproject.toml) ...
error: subprocess-exited-with-error

  × Building wheel for scikit-learn (pyproject.toml) did not run successfully.
... 

I have tried upgrading pip, cython, setuptools but the error still persisted.  
The environment where the error occured: 
Python 3.9.13, 
Windows 10, 
Cython version 3.0.0, 
pip 23.2.1

I also tried installing it in Google Colab and the problem persists. 

Most grateful for any helps.  Thanks !

**Comment by lizgzil** [comment]
Hi @SC-TO - thanks for opening this issue!
It looks like this issue might have been alerted to sklearn recently too - see [this](https://github.com/scikit-learn/scikit-learn/issues/26858)

Looks like using an older version of cython might help things?

Do let us know if you found a solution that worked from that sklearn issue thread and we can update the docs. Thanks!

**Comment by sqr00t** [comment]
Is there a reason to restrict numpy, scipy, and scikit-learn for our ojd package, while packages depending on them (notably scikit-learn for transformers/ sentence-transformers packages) don't restrict them?

On my M1 Mac with Python 3.8, the minimum version for scikit-learn that doesn't run into this issue is 1.2.2, and not restricting scikit-learn results in installing 1.3.0 .

I wonder if expanding on integration gh-action workflows would be helpful in the future, since there isn't tests for other environments besides from ubuntu and our local development (osx-arm64).

It also looks like the only available archives for scikit-learn 0.23.2 are via conda-forge (for Python [3.8](https://anaconda.org/conda-forge/scikit-learn/0.23.2/download/osx-arm64/scikit-learn-0.23.2-py38h397cc00_3.tar.bz2) and [3.9](https://anaconda.org/conda-forge/scikit-learn/0.23.2/download/osx-arm64/scikit-learn-0.23.2-py39hb966dd2_3.tar.bz2)).

Note, awscli==1.27.25 also has a cython related issue on compilation due to it's PyYAML dependency. It could be better practice to not install awscli via pip, since it often has multiple conflicting dependencies.

**Comment by JoseMoreville** [comment]
Got the same issue on M1 even trying the open PR of @lizgzil
