### ISSUE TITLE
do we show 'unmatched' skills in output?

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#79]
for the library or in the OJO pipeline?

**Comment by lizgzil** [comment]
I think since in the [ESCO config](https://github.com/nestauk/ojd_daps_skills/blob/dev/ojd_daps_skills/config/extract_skills_esco.yaml) we have '"max_share": { 1: **0**, ...,' it means that every skill will be matched to at least a level 1 ESCO hierarchy. What we never do (I don't think) is actually code anywhere that if the match is a hierarchy 1 level then this effectively means "unmatched" :/ Easy to do in the analysis, but could be problematic for other users!

**Comment by lizgzil** [comment]
I'm tagging this as documentation, as I don't think we need to change anything but its something to make clear in the documentation

**Comment by lizgzil** [comment]
@india-kerle think we can close this?

**Comment by lizgzil** [comment]
we've made this clearer in the documentation (model card page "The current predefined configurations ensures that every extracted skill will be matched to a taxonomy. However, if a skill is matched to the highest skill group, we label it as ‘unmatched’. Under this definition, for ESCO we identify approximately 2% of skills as ‘unmatched’.")
